# Generated by Django 5.0.6 on 2024-05-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('text', models.TextField(max_length=250, null=True, verbose_name='Описание')),
                ('datedb', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(null=True, upload_to='photos/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Товары(категории)',
                'verbose_name_plural': 'Товары(категории)',
                'ordering': ['-datedb'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('text', models.TextField(max_length=50, null=True, verbose_name='Описание')),
                ('datedb', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('image', models.ImageField(null=True, upload_to='photos/', verbose_name='Картинка')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='products.product')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['-datedb'],
            },
        ),
    ]
